### ISSUE TITLE
Is this repo actively maintained?

### ISSUE THREAD

**Issue by kajensen** [parse-community/ParseReact#181]
Is there any intention to update this repo to support the latest parse javascript sdk (1.9.1 currently)?

**Comment by haydenbleasel** [comment]
I very much doubt it, so I started an unofficial fork called "parse-react-2" to start getting fixes merged.

```
npm install parse-react-2
```

So far, we've merged #26 #47 #88 #131 #179 #174 #166.

**Comment by marcusfelix** [comment]
@haydenbleasel It works with Parse JS SDK ^1.9?

**Comment by haydenbleasel** [comment]
@marcusfelix Yep

**Comment by ericraio** [comment]
@haydenbleasel I can't create new issues on your fork :(

**Comment by haydenbleasel** [comment]
@ericraio That's weird. Fixed it I think.

**Comment by developerX** [comment]
@haydenbleasel I put in a PR to update parseReact to return data and use livequeries you can check it out here if anyone else needs both.
https://github.com/developerX/ParseReact

**Comment by agrcrobles** [comment]
yeah, in fact https://www.parsecdn.com is down

**Comment by acinader** [comment]
I'm gonna try and get it going again.  I am new to react....
