### ISSUE TITLE
Parse+React for new project

### ISSUE THREAD

**Issue by thisfiore** [parse-community/ParseReact#185]
Hi guys, 
Sorry for asking here but it's actually really hard to understand the actual context.

We have a growing project that's built on Parse Server and currently iOS only.
We are trying to understand if react + Parse server is a viable option.

We see that the whole parse-community is being developed but not this repo.

Is this working at the moment?
Is this essential for the react native + parse stack ?

Thank you.

**Comment by Sadmansamee** [comment]
any update on this?
