### ISSUE TITLE
What is recommended for a React Native app?

### ISSUE THREAD

**Issue by c3s4r** [parse-community/ParseReact#192]
In the documentation, it states that ParseReact works with JS SDK up to version `1.6.4`. 

If I want to start a new React Native application now, what is the recommended approach?:

- use this module along with JS sdk 1.6.4? Does this module works for react native?
- use directly the latest JS SDK from my react native app? Will it work?
- Should I use directly the Parse REST API?
- Should I wait?  Is there a timeline for the new starter kit to be available?

**Comment by jinuem** [comment]
I am also wanted to know
 :(

**Comment by c3s4r** [comment]
Closing because I think it's just based on what style you prefer, you can use any of the described approaches.

**Comment by flovilmart** [comment]
There’s also this project https://github.com/andrewimm/parse-lite/ maintained by an ex Parser. It has a different philosophy than other SDK’s but is well thought
